### PR TITLE
ci: Add i18n workflow

### PR DESCRIPTION
**Pull request by jpmckinney**

### CODE REVIEW

**Comment by jpmckinney** [comment]
@yolile Can you coordinate the translation of the new content Duncan added recently?

I noticed this while reviewing the CI setup across repositories (for data registry and others).

**Comment by yolile** [comment]
> @yolile Can you coordinate the translation of the new content Duncan added recently?

Done in CRM-7805

**Comment by yolile** [comment]
The translations are complete now

**Comment by jpmckinney** [comment]
🚀

**Pull request merged**
