### PR TITLE
add example of extensions key

### PR DESCRIPTION
**Pull request by duncandewhurst**
To reference in docs and demonstrate data review tool

### CODE REVIEW

**Comment by jpmckinney** [comment]
I assume this is used by the to-be-integrated content? Unless it is related to something else, I'll merge as part of integrating that content.

**Comment by duncandewhurst** [comment]
yep, I noted in the content doc where the PR needs to be merged

**Comment by jpmckinney** [comment]
This will be integrated verbatim instead of as a static file.

**Comment by jpmckinney** [comment]
Actually, better to put in here.

**Pull request merged**
