### PR TITLE
extension_explorer/templates/publishers.html: Integrate content from …

### PR DESCRIPTION
**Pull request by duncandewhurst**
Closes https://github.com/open-contracting/standard_extension_template/issues/41

### CODE REVIEW

**Comment by jpmckinney** [comment]
Just checking what makes this PR a draft?

**Comment by duncandewhurst** [comment]
Oops, I somehow missed the notification about your comment. Sorry!

It was draft because I needed to resolve the pytest failure. I've done that now.

As well as integrating the content from [how the extensions work](https://github.com/open-contracting/standard_extension_template?tab=readme-ov-file#how-the-extensions-work) I think that we should also integrate the content from [codelists](https://github.com/open-contracting/standard_extension_template?tab=readme-ov-file#codelists). Otherwise, the explanations of schema extensions and codelist extensions will be in different places. I've rewritten the codelist explanation to follow the same style as the schema guidance:

> An extension's codelist CSV files follow the structure of the OCDS codelist files and describe new codelists and codes. To add a new codelist, ensure that your filename does not clash with any existing [codelist filenames](https://standard.open-contracting.org/schema/1__1__5/codelists/). To add codes to an existing codelist, name your file `+<codelist filename>.csv` and ensure that the new codes do not clash with any existing codes. For example, to add 'subcontractor' to `partyRole.csv`, add a file named `+partyRole.csv` to the `codelists` directory and set its content to: 
> 
> ```csv
> Code,Title,Description
> subcontractor,Subcontractor,An organization that will perform part of a contract on behalf of a supplier.
> ```

Shall I add that to this PR?

**Comment by duncandewhurst** [comment]
[Work in progress content](https://docs.google.com/document/d/1Zeap7GGu9xZqcEvI237K6x5-_6MmyK6BhUR3-fW0Fz0/edit)

**Comment by duncandewhurst** [comment]
Continued in https://github.com/open-contracting/standard_extension_template/issues/41#issuecomment-2239192221

**Comment by duncandewhurst** [comment]
Logging the steps I followed so far, for posterity:

1. Convert to HTML using [Google Docs to HTML](https://gopublish.io/tools/google-docs-to-html/)
1. Add translation tags, e.g. for `<h4>` tags: find `<h4>(.*?)</h4>` and replace with `<h4>{{ _("$1") }}</h4>`
1. Use single quotes for link targets: Find `<a href="(.*?)">` and replace with `<a href='$1'>`
1. Add `<code>` tags (manual)
1. Wrap code blocks in `<pre>` and `<code>` tags and remove any HTML and translation tags within the block
1. Remove `` and `` characters
1. Replace pretty apostrophes (`’`) with single quotation marks (`'`)
1. Remove empty tags, e.g. <p></p>

To-do:

* Resolve Flask error
* Check list and blockquote formatting
* Update `id` parameters and relative link targets
* Format using Prettier

**Comment by duncandewhurst** [comment]
@jpmckinney lint test is failing because ruff reports errors on Python files not touched by this PR.

**Comment by jpmckinney** [comment]
Needed to merge `main`.

**Comment by duncandewhurst** [comment]
Ah, I forgot this was an old branch. Thanks!

**Comment by duncandewhurst** [comment]
Leaving as draft pending further input on the needs of extension authors in https://github.com/open-contracting/standard_extension_template/issues/41. Otherwise, this is ready for review.

**Comment by jpmckinney** [comment]
I think we might as well get this PR done and make other changes/improvements later.

@yolile I pushed strings to Transifex: https://app.transifex.com/open-contracting-partnership-1/ocds-extension-explorer/translate/#es/messages/306008985

**Comment by yolile** [comment]
Translated

**Pull request merged**
